### ISSUE TITLE
autopair doesn't work with prezto

### ISSUE THREAD

**Issue by hassan-k** [hlissner/zsh-autopair#6] opened 2016-04-01 09:16 UTC
Hi there,

I recently changed from oh-my-zsh to prezto, and noticed that autopair stops working. I use zgen to manage plugins. Below is a copy of my .zshrc

```
# load zgen
source "${HOME}/.zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
  echo "Creating a zgen save"

  # # theme
  zgen prezto prompt theme 'sorin'

  # # plugins
  zgen prezto
  zgen prezto git
  zgen prezto tmux
  zgen prezto homebrew

  zgen load hlissner/zsh-autopair 'autopair.zsh'
  zgen load zsh-users/zsh-completions
  zgen load felixr/docker-zsh-completion
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-history-substring-search

  zgen save
fi
```

it works once after `zgen reset` and `zgen save`, but if i reload the shell or start another it stops working. 
Seen no problems with oh-my-zsh

**Comment by hlissner** [comment] 2016-04-03 15:47
This is very odd. I'll do some testing today and get back to you!

**Comment by hlissner** [comment] 2016-04-03 18:02
I've discovered the cause. Prezto's Editor module is resetting the keybinds and zgen initializes Prezto's modules last (regardless of zgen load order), thus removing zsh-autopair's bindings.

I don't know how to fix it internally, so you'll have to do this:

```bash
source "${HOME}/.zgen/zgen.zsh"
if ! zgen saved; then
  zgen prezto
  #...
  zgen load hlissner/zsh-autopair 'autopair.zsh'
  #...
  zgen save
fi

# Add this
autopair-init
```

**Comment by hlissner** [comment] 2016-04-05 22:58
I'll close this issue for now. Feel free to reopen if this doesn't fix it for you.

**Closed by hlissner** 2016-04-05 22:58 UTC

**Comment by hassan-k** [comment] 2016-04-06 10:31
👍 Thank you!
